
title: My Resume
url: 'http://junlulocky.com'
baseurl: '' #change it according to your repository name



# Profile information
yourname: Khuram Niaz  ## put your name
title: 'WEB DEVELOPER &amp; GIS PROFESSIONAL'  ## your title
location: Toronto, ON


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url



# Update all the sections by editing the files inside _includes folder.
